"""Subclass of AboutDialog, which is generated by wxFormBuilder."""

import wx
import mdialog
import _version as mwhois_info


# Implementing AboutDialog
class AboutDialog(mdialog.AboutDialog):

    def __init__(self, parent):

        mdialog.AboutDialog.__init__(self, parent)
        self.parent = parent
        self.license_txt = None

        self.parent.Disable()

    # Handlers for AboutDialog events.
    def show_license(self, event):

        with open('files/GPLv2.txt', 'r') as content_file:
            license_txt = content_file.read()

        about = wx.App(False)
        about_frame = LicenseDialog(self, license_txt)
        about.SetTopWindow(about_frame)
        about_frame.CentreOnParent()
        about_frame.Show()
        about.MainLoop()

    def open_project_url(self, event):

        import webbrowser

        webbrowser.open_new_tab(mwhois_info.__website__)
        self.parent.Enable()
        self.Close()

    def close_dialog(self, event):

        self.parent.Enable()
        self.Destroy()


# Implementing LicenseDialog
class LicenseDialog(mdialog.LicenseDialog):

    def __init__(self, parent, license_txt):

        mdialog.LicenseDialog.__init__(self, parent)

        try:
            self.license_txt = license_txt
            self.m_textCtrl1.SetValue(self.license_txt)
            self.parent = parent
            self.parent.Disable()
        finally:
            self.parent.Enable()

    # Handlers for LicenseDialog events.
    def close_license(self, event):

        self.parent.Enable()
        self.Destroy()


class ErrorDialog(mdialog.ErrorDialog):

    def __init__(self, parent):

        mdialog.ErrorDialog.__init__(self, parent)

        try:
            self.parent = parent
            self.parent.Disable()
            self.m_textCtrl_error.SetValue(parent.error_event.data[0])
        finally:
            self.parent.Enable()

    def close_error_dialog(self, event):

        self.parent.Enable()
        self.Destroy()

