"""Subclass of AboutDialog, which is generated by wxFormBuilder."""

from controller import GUIEvent
import mframe


# Implementing AboutDialog
class PropertyDialog(mframe.PropertyDialog):

    def __init__(self, parent):

        mframe.PropertyDialog.__init__(self, parent)

        self.cdate = None
        self.edate = None
        self.udate = None
        self.email = None
        self.reg = None
        self.domain = None
        self.parent = parent
#
        self._setup_properties()

    def _setup_properties(self):

        item = self.parent.m_listctrl_multi.GetFirstSelected()
        status = self.parent.m_listctrl_multi.GetItem(item, 0).GetText()
        self.domain = self.parent.m_listctrl_multi.GetItem(item, 1).GetText()

        if status == 'Not Available':

            self.cdate, self.edate, self.udate, self.email, self.reg = GUIEvent(self).get_domain_properties(self.domain)
            self.m_staticTxt_domain_prop.SetLabel(str(self.domain))
            self.m_staticTxt_cdate_prop.SetLabel(str(self.cdate))
            self.m_staticTxt_edate_prop.SetLabel(str(self.edate))
            self.m_staticTxt_udate_prop.SetLabel(str(self.udate))
            #self.m_staticTxt_email_prop.SetLabel(str(self.email))
            #self.m_staticTxt_reg_prop.SetLabel(str(self.reg))

    def close_prop_box(self, event):

        self.Destroy()